baseURL: "https://khaiwang.github.io/" 
title: Zikai Wang
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: publications/
          weight: 1
        - name: About Me
          url: aboutme/
          weight: 2
        - name: Blog
          url: blogs/
          weight: 3
        - name: News
          url: news/
          weight: 4
params:
    description: "This website hosts Zikai Wang's research papers, blog, curriculum vitae, and contact information."
    author: Zikai Wang
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["blog", "publications", "curriculum vitae"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Zikai Wang
          subtitle: "Iâ€™m a PhD student in Khoury College of Computer Sciences at Northeastern University, advised by Prof. Cheng Tan. Before Northeastern, I obtained my M.E and B.E in Renmin University of China (RUC) under the supervision of Prof. Yunpeng Chai. My research interest lies in building verifiable intelligent systems."
          imageUrl: "me.png"
          imageWidth: 310
          imageHeight: 468
          buttons:
            - name: Publications
              url: publications/
            - name: Blogs
              url: blogs/
            - name: About Me
              url: aboutme/
            - name: News
              url: news/
    socialIcons:
        - name: CV
          url: resume_zikaiwang.pdf
        - name: Email
          url: mailto:wang.zikai1@northeastern.edu
        - name: GitHub
          url: https://github.com/khaiwang
        - name: Twitter
          url: https://x.com/11111Paradox
        - name: LinkedIn
          url: https://www.linkedin.com/in/zikai-wang-b45585286/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Zikai Wang"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2